# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a4dd3f9a15da43ec00674ae36be672a52185df42bdc21224db75074a61185a507cdff3970b2b7501307f5a15d0530b6b1f465701fa1f2b7d7a647f947326ff

test:
  secret_key_base: db227ad43552011c367f5688e543a5943cca8372f904c6b6ff042684994ee49e7a61ad7162a3bcd68b326419ddc8eb298e2fdbc4541190ad4cfd2cb681ee012f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
